name: Build & Push Backend
on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches: ['main']
  pull_request:
  
jobs:
  build-and-push-simple-api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}

      - name: Get tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/simple-api
          # Note: tags has to be all lower-case
          tags: 
            - ${{secrets.DOCKERHUB_USERNAME}}/devops_tp01_api:${{ env.RELEASE_VERSION }}
            - ${{secrets.DOCKERHUB_USERNAME}}/devops_tp01_api:latest
          push: ${{ github.ref == 'refs/heads/main' }}