name: Build & Push front
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build-and-push-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: latest # Optional fallback tag to use when no tag can be found
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./TP2/TP1_ToPipeLine/front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops_front:${{ steps.latesttag.outputs.tag }}, ${{ secrets.DOCKERHUB_USERNAME }}/devops_front:latest
          push: ${{ github.ref == 'refs/heads/main' }}