name: Build & Push HTPP and DB
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build-and-push-databases:
    runs-on: ubuntu-latest
    env:
      working-directory: ./TP2/TP1_ToPipeLine/database
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
            
      - name: Get tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/database
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops_tp01_db:${{ env.RELEASE_VERSION }}, ${{secrets.DOCKERHUB_USERNAME}}/devops_tp01_db:latest
          push: ${{ github.ref == 'refs/heads/main' }}
 
  build-and-push-http:
    runs-on: ubuntu-latest
    env:
      working-directory: ./TP2/TP1_ToPipeLine/http
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: latest # Optional fallback tag to use when no tag can be found

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
    
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/http
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops_httpd:${{ steps.latesttag.outputs.tag }}, ${{secrets.DOCKERHUB_USERNAME}}/devops_httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
