name: Build & Push front
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build-and-push-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
      
      - name: Get tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/front
          tags: 
            - ${{ secrets.DOCKERHUB_USERNAME }}/devops_front:${{ env.RELEASE_VERSION }}
            - ${{ secrets.DOCKERHUB_USERNAME }}/devops_front:latest
          push: ${{ github.ref == 'refs/heads/main' }}