name: Build & Push HTPP and DB
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: ['main']
  pull_request:

jobs:
  build-and-push-databases:
    runs-on: ubuntu-latest
    env:
      working-directory: ./TP2/TP1_ToPipeLine/database
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/database
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops_tp01_db:1.2
          push: ${{ github.ref == 'refs/heads/main' }}
 
  build-and-push-http:
    runs-on: ubuntu-latest
    env:
      working-directory: ./TP2/TP1_ToPipeLine/http
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./TP2/TP1_ToPipeLine/http
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/devops_httpd:1.2
          push: ${{ github.ref == 'refs/heads/main' }}
