# name: Deploy application
# on:
#   workflow_run:
#     workflows: ["Build & Push Backend"]
#     types:
#       - completed
#     branches: ['main']
#   pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./TP3/playbook.yaml
          key: ${{secrets.SERVER_RSA}}
          inventory: |
            all:
              vars:
                ansible_user: centos
              children:
                prod:
                  hosts: mathieu.eriau.takima.cloud
