# name: Deploy application
# on:
#   workflow_run:
#     workflows: ["Build & Push Backend"]
#     types:
#       - completed
#     branches: ['main']
#   pull_request:

name: Deploy application
on:
  push:
    branches: ['main']
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set ansible config secrets
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_RSA }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password
          mkdir ./.ssh
          echo "$SERVER_SSH_KEY" > ./.ssh/id_rsa
          chmod 600 ./.ssh/id_rsa
      - name: run exporters playbook
        run: |
          pwd
          ls -all
          ansible-playbook -i ./TP3/inventories/setup.yaml ./TP3/playbook.yaml
